### ISSUE TITLE
Force DHW from scheduler only once?

### ISSUE THREAD

**Issue by Fonzie66** [edterbak/NodeRed_Heishamon_control#38]
I have an ODROID N2+ running homeassistant and the Nodered integration installed. A heishamon latest issue is connected to my Panasonic 5kW J serie heatpump. In the past time I have put the heishamon on the write port. After one year last week I relocated it to the read port. Panasonic CZ-TAW was removed.

I implemented the homeassistant integration I can read and write values.

Now I have also implemented the Nodered automation for control of the aquarea. I can see MQTT command are sent every two minutes for " SetZ1HeatRequestTemperature" depending on room and outside temperature, so for now I assumes this works correctly.
 
I have scheduled a " Force DHW"  from the Node Red dashboard set at a certain time every day.
This works the first day this schedule has to be performed. I see in the log files of the dashboard that the correct data is sent to Heishamon.
The second day , and every following day, this doesn't work, the correct data is sent but the pana doesn't react.
To get this working again I have to manually reset the " Force DHW" button in the Nodered home dashboard. So to get the scheduler to work I have to reset this button every day.
I also noticed that this Force DHW on the Nodered home display reacts differently from the home assistant force DHW button. The former stays on after it is set, and the latter button jumps back after some time, which in my opinion is corrrect.
 
I am not familiar enough with Nodered to debug this part of the programm, I hope you can share your thoughts on this one.

**Comment by edterbak** [comment]
Sorry for the late reply. I do not get a notification other than in my spambox. 

But; Thank you for posting this issue.
I will look into it soon.

As a side note: (because this does not solve the issue you reported...)
The force DHW option is not my first choice to run each day. The manual I have here says this about the function of it.
```
Powerful Operation:
Powerful mode is use to increase the capacity of heat pump to achieve higher target temperature. Powerful mode is applicable when heat mode is operating.

Force DHW:
Purpose:
When user want to use hot water now, user can press this force DWH mode under the quick menu to operate tank only mode to boil up the tank temperature.
```
From my understanding, the force DHW will boost the water temperature at the cost of efficiency. 
Personally I have set the scheduler to operationmode DHW only at 13h00 and at 14h30 back to HEAT only.

In the dashboard, if you flick the toggle Force DHW, it will not work if you do not have DHW in the current operating mode. 
This is expected and as panasonic built it. (see text above from the manual)

The expected behaviour of Force DHW through the **scheduler** should be:
- change operating mode to add DHW
- turn on Force DHW 
- ... execute dhw run 
- once DHW target is reached
- change operating mode to remove DHW
- turn off Force DHW

**Comment by edterbak** [comment]
@Fonzie66 
could you give more info on your setup.
What functions are you using, and (roughly) what are the settings?

**Comment by Fonzie66** [comment]
You reply is not late at all.
I will answer to both of your mails here:

I am using force DHW not to boost the temperature but to heat up the boiler to its setpoint when the outside temperature is higher (for efficiency) and to be sure the HP is doing a DHW run when the solar panels provide power. Not absolute necessary for now but will be convenient in a few years.

So for me this is a kind of test which is more efficient: force DHW at a predetermined time once a day or just let the HP heat up the boiler when the lower threshold is reached. I can log every parameter including power usage with an external power meter in Grafana so that should provide some insight.

What I see now is that the force DHW once a day uses about half an hour to heat up the boiler to its setpoint again. Normal operating uses about an hour but of course happens less often. Also the compressor frequency is higher.

As far as I can see from the Grafana graphs this function doesn’t actually lead to a higher DHW end temperature in relation to a normal DHW run which is activated when the lower threshold is reached, <47 (52-5) in my case. It is not my purpose either. 
At the moment the HP is set to DHW only from the HP display, so I only see the tap symbol in the HP disply now.
Should I change this operation mode from the scheduler since you mention “ change operating mode to add DHW”?
![HP_settings_home_page](https://user-images.githubusercontent.com/93837831/178141675-61bb293a-af17-4a49-a95a-728c965573a7.png)

Attached the setting from the home screen.
![HP_settings_operating_modes](https://user-images.githubusercontent.com/93837831/178141753-3ae33d31-eb20-4835-b86b-06f2409ac2a0.png)

**Comment by edterbak** [comment]
Nice, thank you for your reply. 

The target temperature of the DHW remains the same if you use Force DHW or regular DHW run. The only difference is (from what I understood) that the 'force' option does this as quick as possible. So it is less efficient. The usecase for this is that you know a lot of DHW is going to be used. 

Can you post a screenshot of RTC function?

_"Should I change this operation mode from the scheduler since you mention “ change operating mode to add DHW”?"_
No. I see now that I was not very clear on this. That should not be required. 
The intended functionality as I designed it is that you can add in scheduler a forceDHW run. If you set only this task (forcedhw) through the scheduler, it should automatically set the correct Operating Mode for you. 
The steps I mention above, the bullits in the previous post, this is all automatically done. 

atleast, that is how I intended it to be 😄 

Also, this reminds me that I need to take a lot more care of the information around this stuff. I will put this in the FAQ, and I will mak a nice help page as with the SOLAR tab of this flow. After your bug is fixed.

**Comment by Fonzie66** [comment]
**The target temperature of the DHW remains the same if you use Force DHW or regular DHW run. The only difference is (from what I understood) that the 'force' option does this as quick as possible. So it is less efficient. The usecase for this is that you know a lot of DHW is going to be used.**

OK I will keep an closer eye on the behavior in force DHW mode or normal DHW mode. Maybe due to the relatively high outside temperature at the moment, even the force mode doesn’t need a high compressor frequency to get to the heating energy needed for DHW use. But that’s an assumption.

Regarding the available information: I know from experience how hard it Is to make a manual/information of any kind, of something that has been in your mind for so long and you yourself know inside out.   
For now I like to say how much a lot of people appreciate the work you put in this. It must cost you an enormous amount of time. Lots of critical people judging what you do. Thanks.  

Below the RTC screenshot.

![Nodered_RTC_settings](https://user-images.githubusercontent.com/93837831/178150232-eaede209-f12f-4c59-97a9-3a2e71d34fef.png)

**Comment by edterbak** [comment]
Did you update to the latest version? V17.5
In there, there is a fix in rtc funtion.
If i am lucky, this helps you to. If not, i need to dig in deep. Gheheh...

In the main github page there is an animated gif on how to update.

**Comment by Fonzie66** [comment]
I will try this when In can. Unfortunately my spare time is limited during normal weekdays. I will keep you informed. Thanks.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by edterbak** [comment]
2nd day now, and the Force DHW has been triggered as intended by the scheduler. 
So it seems I can not reproduce the issue you describe (that the first time it does run, 2nd time not)

**Comment by edterbak** [comment]
Next release (18.0) contains a little extra rework of the force DHW toggle. Hopefully this helps a bit.

**Comment by edterbak** [comment]
@Fonzie66 Do you have an update on your end?

It seems there is something not going correctly at my end. 
It might be related to your seen behaviour. Just to let you know.

I will keep you posted if I find something related.
but I will be away for ~4 weeks soon.

**Comment by Fonzie66** [comment]
Hi no not really. I have changed the Heishamon YAML file to match the latest changes in the new HomeAssitant MQTT format but with no result. For now I set the force DHW from home assiatant now and leave it for the time beeing.
I will look forward to your updates if you find something after your Holiday, enjoy!

**Comment by edterbak** [comment]
@Fonzie66 
Did you run into issues further related to this?

If not, I would like to close the bug-report.

**Comment by Fonzie66** [comment]
You can close this report. I am closely monitoring progress on Tweakers to stay up to date. As soon as you release the working NR flows I will make a new attempt.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by edterbak** [comment]
Ok. 👍
