### ISSUE TITLE
Heatpump direct mode

### ISSUE THREAD

**Issue by Human3322** [edterbak/NodeRed_Heishamon_control#47]
First of all, thanks for your fantastic work especially when electric price is crazy.

I have a Panasonic Aquarea T-Cap 9kw and wonder if anyone have some information about putting it in "direct" mode as stated in section 4?

Regards
Olle

**Comment by edterbak** [comment]
Sorry, I just noticed your question. I am adding this info in some more details. 

Here you find the setting in your thermostat. This is from my manual a 7kw Pana J.

<img src="https://github.com/edterbak/NodeRed_Heishamon_control/blob/main/images/manual%20-%20direct1.png?raw=true">

<img src="https://github.com/edterbak/NodeRed_Heishamon_control/blob/main/images/manual%20-%20direct2.png?raw=true">

**Comment by edterbak** [comment]
If you are a Dutch reader, you can join a forum where there is a lot of activity on/about my node red flow. 
https://gathering.tweakers.net/forum/list_messages/2108208?data%5Bfilter_topicstarter%5D=1

**Comment by Human3322** [comment]
I forgot to ask you what Virtual SP (Ta) have for meaning?
Have it any function if I use WAR?
And should "Pump max flow" be 100% default?
Thanks for your great work.

**Comment by edterbak** [comment]
WAR replaces the virt sp. 
Pump flow max was originally at 45% in my case. 
It is difficult to say what it should be. Depends on so many thing.

**Comment by Human3322** [comment]
Thanks
Is it possible to get a screenshot of WAR and RTC as an example, a picture tell more than a thousand words ;-)

**Comment by edterbak** [comment]
I think it is best to use this version of the node red flow

https://github.com/edterbak/NodeRed_Heishamon_control/blob/20beta/flows.json

Here are the pictures of my settings.

<img src="https://github.com/edterbak/NodeRed_Heishamon_control/blob/main/images/warsettings.png">

<img src="https://github.com/edterbak/NodeRed_Heishamon_control/blob/main/images/warsettings2.png">

**Comment by edterbak** [comment]
@Human3322 
Currently, it is not required anymore to use DIRECT mode. 
You can now also use the compensation curve setting. 
You can program it through the dashboard. 

Be aware you only can use 2 temperature points. not three like in the node red flow. Panasonic native has 2 points. 

If you are going to try this. the WAR function wil auto-disable.
I would advice NOT to use the softstart function with 'Max water temp. increase' of > 0. fix it to 0, otherwise you might get hot :) 

This is still a bit experimental, but it works on my end for a day or two.
